boost: false
boost amount: 2
level roles:
  shark squad: 
    level 0: 1462838462150606871
    level 1: 1462838496317276349
    level 2: 1462838512993697975
    level 3: 1462838533940056236
    level 4: 1462838552634200229
    level 5+: 1462832730176880771